/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MarketplaceManagementRouteImport } from './routes/marketplace-management'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceManagementRoute = MarketplaceManagementRouteImport.update({
  id: '/marketplace-management',
  path: '/marketplace-management',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/contact': typeof ContactRoute
  '/marketplace-management': typeof MarketplaceManagementRoute
  '/packages': typeof PackagesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/contact': typeof ContactRoute
  '/marketplace-management': typeof MarketplaceManagementRoute
  '/packages': typeof PackagesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/contact': typeof ContactRoute
  '/marketplace-management': typeof MarketplaceManagementRoute
  '/packages': typeof PackagesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/contact'
    | '/marketplace-management'
    | '/packages'
    | '/privacy-policy'
    | '/resources'
    | '/services'
    | '/solutions'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/contact'
    | '/marketplace-management'
    | '/packages'
    | '/privacy-policy'
    | '/resources'
    | '/services'
    | '/solutions'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/contact'
    | '/marketplace-management'
    | '/packages'
    | '/privacy-policy'
    | '/resources'
    | '/services'
    | '/solutions'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ContactRoute: typeof ContactRoute
  MarketplaceManagementRoute: typeof MarketplaceManagementRoute
  PackagesRoute: typeof PackagesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  SolutionsRoute: typeof SolutionsRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace-management': {
      id: '/marketplace-management'
      path: '/marketplace-management'
      fullPath: '/marketplace-management'
      preLoaderRoute: typeof MarketplaceManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  ContactRoute: ContactRoute,
  MarketplaceManagementRoute: MarketplaceManagementRoute,
  PackagesRoute: PackagesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  SolutionsRoute: SolutionsRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
